# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing

import baml_py
import typing_extensions

from . import stream_types, type_builder, types
from .globals import \
    DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import BamlCallOptions, DoNotUseDirectlyCallManager


class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(
        self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        collector: typing.Optional[
            typing.Union[
                baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]
            ]
        ] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[
            typing.Callable[[str, baml_py.baml_py.FunctionLog], None]
        ] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
        return self.__stream_client

    @property
    def request(self):
        return self.__http_request

    @property
    def stream_request(self):
        return self.__http_stream_request

    @property
    def parse(self):
        return self.__llm_response_parser

    @property
    def parse_stream(self):
        return self.__llm_stream_parser

    def ExtractMedicalAlerts(
        self,
        document: str,
        alert_types: typing.List["types.AlertType"],
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.MedicalAlert"]:
        # Check if on_tick is provided
        if "on_tick" in baml_options:
            stream = self.stream.ExtractMedicalAlerts(
                document=document, alert_types=alert_types, baml_options=baml_options
            )
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(
                function_name="ExtractMedicalAlerts",
                args={
                    "document": document,
                    "alert_types": alert_types,
                },
            )
            return typing.cast(
                typing.List["types.MedicalAlert"],
                result.cast_to(types, types, stream_types, False, __runtime__),
            )

    def ExtractResume(
        self,
        resume: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Resume:
        # Check if on_tick is provided
        if "on_tick" in baml_options:
            stream = self.stream.ExtractResume(resume=resume, baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(
                function_name="ExtractResume",
                args={
                    "resume": resume,
                },
            )
            return typing.cast(
                types.Resume,
                result.cast_to(types, types, stream_types, False, __runtime__),
            )


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractMedicalAlerts(
        self,
        document: str,
        alert_types: typing.List["types.AlertType"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[
        typing.List["stream_types.MedicalAlert"], typing.List["types.MedicalAlert"]
    ]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(
            function_name="ExtractMedicalAlerts",
            args={
                "document": document,
                "alert_types": alert_types,
            },
        )
        return baml_py.BamlSyncStream[
            typing.List["stream_types.MedicalAlert"], typing.List["types.MedicalAlert"]
        ](
            result,
            lambda x: typing.cast(
                typing.List["stream_types.MedicalAlert"],
                x.cast_to(types, types, stream_types, True, __runtime__),
            ),
            lambda x: typing.cast(
                typing.List["types.MedicalAlert"],
                x.cast_to(types, types, stream_types, False, __runtime__),
            ),
            ctx,
        )

    def ExtractResume(
        self,
        resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.Resume, types.Resume]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(
            function_name="ExtractResume",
            args={
                "resume": resume,
            },
        )
        return baml_py.BamlSyncStream[stream_types.Resume, types.Resume](
            result,
            lambda x: typing.cast(
                stream_types.Resume,
                x.cast_to(types, types, stream_types, True, __runtime__),
            ),
            lambda x: typing.cast(
                types.Resume, x.cast_to(types, types, stream_types, False, __runtime__)
            ),
            ctx,
        )


class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractMedicalAlerts(
        self,
        document: str,
        alert_types: typing.List["types.AlertType"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(
            function_name="ExtractMedicalAlerts",
            args={
                "document": document,
                "alert_types": alert_types,
            },
            mode="request",
        )
        return result

    def ExtractResume(
        self,
        resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(
            function_name="ExtractResume",
            args={
                "resume": resume,
            },
            mode="request",
        )
        return result


class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractMedicalAlerts(
        self,
        document: str,
        alert_types: typing.List["types.AlertType"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(
            function_name="ExtractMedicalAlerts",
            args={
                "document": document,
                "alert_types": alert_types,
            },
            mode="stream",
        )
        return result

    def ExtractResume(
        self,
        resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(
            function_name="ExtractResume",
            args={
                "resume": resume,
            },
            mode="stream",
        )
        return result


b = BamlSyncClient(DoNotUseDirectlyCallManager({}))
